version: '3.8'

services:
  gister:
    image: itwala/gister:latest
    env_file:
      - ./env/gister.env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - gister_network


  mongodb:
    image: mongo:8.0.15
    command: ["mongod", "--bind_ip_all"]
    env_file:
      - ./env/mongodb.env
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./script/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - gister_network


networks:
  gister_network:
    driver: bridge
    attachable: true

